### PR TITLE
Add SVG support

### PR DESCRIPTION
**Pull request by samuelh2005**
This adds support for rendering SVG images. SVG images are good because if you make the width / height bigger then the orignal image the image quality will be the same (useful for signs).

To parse SVGs the [jsvg](https://github.com/weisJ/jsvg) has been included and an additional [DisplayLayerSVGImage](https://github.com/ajh123/fabric-webstreamer/blob/dev/svg/src/main/java/fr/theorozier/webstreamer/display/render/DisplayLayerSVGImage.java) class was added. This class pulls the SVG from the URL, uses jsvg to convert it to a PNG which then gets displayed in a similar way to other images. The WebDisplay's `width` and `height` variables are used to scale the SVG.

# Demonstration
* PNG version
image
* SVG version (notice the sharper text)
image

### CODE REVIEW

**Comment by theorzr** [comment]
Thank you, I'm reviewing the changes, there are some changes to be made (mostly because I never thought of SVG and some classes were not ready for it).

**Review by theorzr — CHANGES_REQUESTED** [review]
Hi! Thank you so much for working on this, this is really great. 

I spotted a bug in your implementation, basically the first rendered SVG layer for a given URI will define the resolution of all displays that are also using this URI. To fix this, I've been thinking of a way to return a layer depending on more parameters than the simple URI, and I've reworked a lot of things in the `v1.5` branch that is now published on this repo. Basically, you will have to create a new class extending `DisplayLayerMap` and use a key that group width/height and just implement the `getLayerKey` method and `getNewLayer` that returns an SVG image layer. You can then add the condition matching `.svg` paths in `DisplayLayerManager` class (like before), and return your `DisplayLayerMap` subclass.

Another problem in my opinion is that the SVG layer class is almost a duplicate of the image one, to fix this I've slightly improved the design of the static image layer, I think you can now just subclass it and give the render size in the constructor.

I also removed the `DisplayUrl` class, it was basically useless because we can just use the URI to map our layers.

The rework I've made are likely to merge conflict, I encourage you to just reset your branch (keeping your work backup) and just copy the important parts.

Also, please retarget this merge request to the `v1.5` branch! If you have more question, do not hesitate!

**Comment by samuelh2005** [comment]
Thanks

**Comment by samuelh2005** [comment]
@mindstorm38 

In my `dev/svg2` branch I've made a [DisplayLayerSVGImage.java](https://github.com/ajh123/fabric-webstreamer/commit/8fba2dae06809e0073e921819dad47a2a2a39520#diff-1d271094971cead4497177023b9f3509be7787f9689460ca806bf6276fb5ec66) and a [DisplayLayerSVGMap.java](https://github.com/ajh123/fabric-webstreamer/commit/8fba2dae06809e0073e921819dad47a2a2a39520#diff-c8a2a05190675157dfa14dd02529a196178498772238a8eb18aa047ea1495e40).

Where would you call the constructor for `DisplayLayerSVGMap`?

**Comment by theorzr** [comment]
This is great! I don't think that you have to make a record containing URI (it is redundant for the hash as map key), you can also move it to the map class I think. Passing the integer directly to the constructor. To answer your question, you just have to add a else-if case in `DisplayLayerManager::getNewLayer` and this should be it! It might be needed to pass the resource and keep it in your map class (maybe improved later, but anyway this will be good enough).

**Comment by samuelh2005** [comment]
Closed, see #28 for more details.

**Pull request closed without merging**
